LOCAL_PATH := $(call my-dir)

CODINARAMFS_OUT_RAM := $(CODINARAMFS_OUT)/ramdisk

CODINARAMFS_BUILD_TARGET_INT:
	$(ACP) $(LOCAL_PATH)/busybox $(CODINARAMFS_OUT_RAM)/busybox
	$(ACP) $(LOCAL_PATH)/stage0 $(CODINARAMFS_OUT_RAM)/stage0
	$(ACP) $(LOCAL_PATH)/stage1 $(CODINARAMFS_OUT_RAM)/stage1
	$(ACP) $(LOCAL_PATH)/boot.cpio $(CODINARAMFS_OUT_RAM)/boot.cpio
	$(ACP) $(LOCAL_PATH)/recovery.cpio $(CODINARAMFS_OUT_RAM)/recovery.cpio

CODINARAMFS_BUILD_TARGET += CODINARAMFS_BUILD_TARGET_INT

