#!/ramdisk/busybox sh

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

load_image=/ramdisk/boot.cpio

if ! busybox grep -q bootmode=2 /proc/cmdline ; then
	
	# Check for SD boot flag from cache partition.
	
	echo "Not booting into recovery..."
	load_sd="0"
	
	if busybox mount -t ext4 /dev/block/mmcblk0p4 /cache ; then
		
		if busybox test -e /cache/enable_sdboot ; then
			load_sd="1"
			busybox rm /cache/enable_sdboot
		fi
		
		busybox umount /cache
		
	else
		echo "Unable to mount cache partition."
	fi
	
	# Enable SD boot if asked to.
	
	if busybox test "$load_sd" -eq "1" ; then
		
		echo "SD boot flag is enabled, loading..."
		
		if busybox mount -t ext4 /dev/block/mmcblk1p2 /mnt/disk0 ; then
			
			if busybox cp /mnt/disk0/ramdisk.cpio /ramdisk/sdboot.cpio ; then
				load_image=/ramdisk/sdboot.cpio
			else
				echo "Unable to copy ramdisk.cpio from SD boot."
			fi
			
			busybox umount /mnt/disk0
			
		else
			echo "Unable to mount SD boot partition."
		fi
		
	else
		echo "SD boot flag is disabled."
	fi
	
else
	
	echo "Booting into recovery..."
	echo "Not checking for SD boot flag."
	
	if busybox test -r /ramdisk/recovery.cpio ; then
		load_image=/ramdisk/recovery.cpio
	fi
	
fi

# Load specified image to the ramdisk.

echo
echo "Loading image: ${load_image}"

busybox cpio -i < "${load_image}"

busybox umount /sys
busybox umount /proc

echo
echo "stage1 is finished."

