#!/ramdisk/busybox sh

busybox mkdir -p /proc /sys /mnt

busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

load_image=/ramdisk/boot.cpio

if ! busybox grep -q bootmode=2 /proc/cmdline ; then
	
	# Check for SD boot flag.
	
	echo "Not booting into recovery..."
	
	if busybox mount -t ext4 /dev/block/mmcblk1p2 /mnt ; then
		
		if busybox test -e /mnt/enable_sdboot ; then
			
			busybox rm /mnt/enable_sdboot
			
			echo "SD boot flag is enabled, loading..."
			
			if busybox cp /mnt/ramdisk.cpio /ramdisk/sdboot.cpio ; then
				load_image=/ramdisk/sdboot.cpio
			else
				echo "Unable to copy ramdisk.cpio from SD boot."
			fi
			
		else
			echo "SD boot flag is disabled."
		fi
		
		busybox umount /mnt
		
	else
		echo "Unable to mount SD boot partition."
	fi
	
else
	
	echo "Booting into recovery..."
	echo "Not checking for SD boot flag."
	
	if busybox test -r /ramdisk/recovery.cpio ; then
		load_image=/ramdisk/recovery.cpio
	fi
	
fi

busybox umount /sys
busybox umount /proc

busybox rm -fr /dev
busybox rmdir /proc /sys /mnt

# Load specified image to the ramdisk.

echo
echo "Loading image: ${load_image}"

busybox cpio -i < "${load_image}"

echo
echo "stage1 is finished."

